# Generated by Django 4.2.7 on 2023-11-09 15:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vin', models.CharField(max_length=200, unique=True)),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('hp_or_cc', models.CharField(max_length=50)),
                ('model_id', models.CharField(max_length=50)),
                ('engine_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('vehicle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclemodel')),
            ],
        ),
    ]
